// Top-level build file
buildscript {
    repositories {
        google()
        mavenCentral() 
 
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.1.0'
        classpath 'io.fabric.tools:gradle:1.24.4'
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" } 
        google()
        mavenCentral()
        
        // Add this specific mirror for older libraries
        
    }
}

ext {
    compileSdkVersion = 26
    buildToolsVersion = '27.0.1'
    targetSdkVersion = 26
    minSdkVersion = 19
    googleServiceVersion = "11.6.2"
    supportLibVersion = "27.0.2"
}
